# Generated by Django 5.1rc1 on 2024-08-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("student", "date")},
        ),
    ]
