# Generated by Django 5.1rc1 on 2024-08-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendancerecord_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="New_Commers_Validate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=100)),
                ("l_name", models.CharField(max_length=100)),
                ("roll_no", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=10)),
                ("face_encoding", models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
