# Generated by Django 5.1rc1 on 2024-08-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_new_commers_validate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new_commers_validate",
            name="phone",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
