# Generated by Django 5.1 on 2024-09-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_new_commers_validate_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("desc", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="new_commers_validate",
            name="face_encoding",
        ),
    ]
