# Generated by Django 5.1 on 2024-09-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_contact_remove_new_commers_validate_face_encoding"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="new_commers_validate",
            unique_together={("f_name", "l_name")},
        ),
    ]
